// Code generated by Prismic. DO NOT EDIT.

import About from "./About";
import Benefits from "./Benefits";
import Contact from "./Contact";
import ContactCta from "./ContactCta";
import Footer from "./Footer";
import Header from "./Header";
import Hero from "./Hero";
import HowWeWork from "./HowWeWork";
import PageHeader from "./PageHeader";
import ParallaxFacts from "./ParallaxFacts";
import Services from "./Services";
import Testimonials from "./Testimonials";

export const components = {
	about: About,
	benefits: Benefits,
	contact: Contact,
	contact_cta: ContactCta,
	footer: Footer,
	header: Header,
	hero: Hero,
	how_we_work: HowWeWork,
	page_header: PageHeader,
	parallax_facts: ParallaxFacts,
	services: Services,
	testimonials: Testimonials
};