// Code generated by Slice Machine. DO NOT EDIT.
import dynamic from "next/dynamic";

export const components = {
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  page_header: dynamic(() => import("./PageHeader")),
  about: dynamic(() => import("./About")),
  services: dynamic(() => import("./Services")),
  parallax_facts: dynamic(() => import("./ParallaxFacts")),
  contact_cta: dynamic(() => import("./ContactCta")),
  benefits: dynamic(() => import("./Benefits")),
  testimonials: dynamic(() => import("./Testimonials")),
  how_we_work: dynamic(() => import("./HowWeWork")),
  contact: dynamic(() => import("./Contact")),
  footer: dynamic(() => import("./Footer")),
};
